POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "Product 3",
    "price": 300
}

###

GET http://localhost:8000/products/dfca8046-9e27-4121-9ce8-4b231c388c4b HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk2MzI0MzMsInN1YiI6IjY4MWZlMWRhLTkyOTQtNGMzZi05M2ZlLTQ2NzFkZTU5NTg3OCJ9.SyAkOM3806rq-D75zqTyGHuEieKgl5b-CmLMNS1XkzQ


###

PUT http://localhost:8000/products/dfca8046-9e27-4121-9ce8-4b231c388c4b HTTP/1.1
Content-Type: application/json

{
    "name": "Update works!",
    "price": 10000
}

###

DELETE http://localhost:8000/products/dfca8046-9e27-4121-9ce8-4b231c388c4b HTTP/1.1
Content-Type: application/json
